name: Build on Push
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: upload-artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: 112
          path: /home/runner/work/container-passthrough/container-passthrough/target/*.jar